In [2]:
import pandas as pd

df = pd.DataFrame({
    "Age": [18, 22, 25, 30, 35, 40],
    "Salary": [15000, 25000, 30000, 45000, 60000, 80000],
    "Experience": [0, 1, 2, 5, 8, 12]
})

df

   Age  Salary  Experience
0   18   15000           0
1   22   25000           1
2   25   30000           2
3   30   45000           5
4   35   60000           8
5   40   80000          12

In [ ]:
#Standard scaler
age = df[["Age"]]
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
age_scaled = scaler.fit_transform(age)
age_scaled
df["Scaled_Age"] = age_scaled

   Age  Salary  Experience  Scaled_Age
0   18   15000           0   -1.370019
1   22   25000           1   -0.839689
2   25   30000           2   -0.441942
3   30   45000           5    0.220971
4   35   60000           8    0.883883
5   40   80000          12    1.546796

In [6]:
salary = df[["Salary"]]
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
salary_scaled =mm.fit_transform(salary)
df["Scaled_Salary"] = salary_scaled
df

   Age  Salary  Experience  Scaled_Age  Scaled_Salary
0   18   15000           0   -1.370019       0.000000
1   22   25000           1   -0.839689       0.153846
2   25   30000           2   -0.441942       0.230769
3   30   45000           5    0.220971       0.461538
4   35   60000           8    0.883883       0.692308
5   40   80000          12    1.546796       1.000000

In [7]:
experience = df[["Experience"]]
from sklearn.preprocessing import MinMaxScaler
mmScaler = MinMaxScaler()
experience_scaled =mmScaler.fit_transform(experience)
df["Scaled_Experience"] = experience_scaled
df

   Age  Salary  Experience  Scaled_Age  Scaled_Salary  Scaled_Experience
0   18   15000           0   -1.370019       0.000000           0.000000
1   22   25000           1   -0.839689       0.153846           0.083333
2   25   30000           2   -0.441942       0.230769           0.166667
3   30   45000           5    0.220971       0.461538           0.416667
4   35   60000           8    0.883883       0.692308           0.666667
5   40   80000          12    1.546796       1.000000           1.000000