In [13]:
import pandas as pd


df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"],
    "Education": ["School", "Bachelor", "Master", "PhD", "Bachelor", "Master"],
    "City": ["Ahmedabad", "Mumbai", "Delhi", "Ahmedabad", "Delhi", "Mumbai"]
})
df

   Gender Education       City
0    Male    School  Ahmedabad
1  Female  Bachelor     Mumbai
2    Male    Master      Delhi
3  Female       PhD  Ahmedabad
4    Male  Bachelor      Delhi
5  Female    Master     Mumbai

In [14]:
# Label Encoding
gender = df[["Gender"]]
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
gender_encoded = encoder.fit_transform(gender)
gender_encoded
df["Gender_encoded"] = gender_encoded
df
df = df.drop(columns=["Gender"])
df

C:\Users\KARAN\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

  Education       City  Gender_encoded
0    School  Ahmedabad               1
1  Bachelor     Mumbai               0
2    Master      Delhi               1
3       PhD  Ahmedabad               0
4  Bachelor      Delhi               1
5    Master     Mumbai               0

In [15]:
# One hot Encoded
city = df[["City"]]
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)
city_encoded = ohe.fit_transform(city)
city_names = ohe.get_feature_names_out(["City"])
city_names

city_encoded = pd.DataFrame(city_encoded, columns=city_names)
city_encoded

df = pd.concat([df, city_encoded], axis=1)
df = df.drop(columns=["City"])
df

  Education  Gender_encoded  City_Delhi  City_Mumbai
0    School               1         0.0          0.0
1  Bachelor               0         0.0          1.0
2    Master               1         1.0          0.0
3       PhD               0         0.0          0.0
4  Bachelor               1         1.0          0.0
5    Master               0         0.0          1.0

In [19]:
# Ordinal Encoder
education = df[["Education"]]
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[["School", "Bachelor", "Master", "PhD"]])
education_encoded = oe.fit_transform(education)
education_encoded
df["Education_Encoded"] = education_encoded
df = df.drop(columns=["Education"])
df

   Gender_encoded  City_Delhi  City_Mumbai  Education_Encoded
0               1         0.0          0.0                0.0
1               0         0.0          1.0                1.0
2               1         1.0          0.0                2.0
3               0         0.0          0.0                3.0
4               1         1.0          0.0                1.0
5               0         0.0          1.0                2.0