In [16]:
# OneHotEncoder converts nominal (unordered) categories into binary (0/1) columns.

In [17]:
import pandas as pd
import numpy as np
df = pd.read_csv("../encoding_practice.csv")

# City Column
city = df[["City"]]
city

         City
0   Ahmedabad
1      Mumbai
2   Ahmedabad
3       Surat
4       Delhi
5      Mumbai
6        Pune
7   Ahmedabad
8       Surat
9       Delhi
10       Pune
11     Mumbai

In [18]:
from sklearn.preprocessing import OneHotEncoder
# sparse_output=False returns a standard array
ohe = OneHotEncoder(sparse_output=False, drop="first")
encoded_city = ohe.fit_transform(city)
encoded_city

array([[0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.]])

In [19]:
# take out the unique names from city column
names_of_city = ohe.get_feature_names_out(["City"])
names_of_city

array(['City_Delhi', 'City_Mumbai', 'City_Pune', 'City_Surat'],
      dtype=object)

In [20]:
city_encoded_df = pd.DataFrame(encoded_city, columns=names_of_city)
city_encoded_df

    City_Delhi  City_Mumbai  City_Pune  City_Surat
0          0.0          0.0        0.0         0.0
1          0.0          1.0        0.0         0.0
2          0.0          0.0        0.0         0.0
3          0.0          0.0        0.0         1.0
4          1.0          0.0        0.0         0.0
5          0.0          1.0        0.0         0.0
6          0.0          0.0        1.0         0.0
7          0.0          0.0        0.0         0.0
8          0.0          0.0        0.0         1.0
9          1.0          0.0        0.0         0.0
10         0.0          0.0        1.0         0.0
11         0.0          1.0        0.0         0.0

         City  City_Delhi  City_Mumbai  City_Pune  City_Surat
0   Ahmedabad         0.0          0.0        0.0         0.0
1      Mumbai         0.0          1.0        0.0         0.0
2   Ahmedabad         0.0          0.0        0.0         0.0
3       Surat         0.0          0.0        0.0         1.0
4       Delhi         1.0          0.0        0.0         0.0
5      Mumbai         0.0          1.0        0.0         0.0
6        Pune         0.0          0.0        1.0         0.0
7   Ahmedabad         0.0          0.0        0.0         0.0
8       Surat         0.0          0.0        0.0         1.0
9       Delhi         1.0          0.0        0.0         0.0
10       Pune         0.0          0.0        1.0         0.0
11     Mumbai         0.0          1.0        0.0         0.0