In [7]:
import pandas as pd

df = pd.read_csv("../../PRACTICE CSV FILES/student_performance_large.csv")

df

     StudyHours  Attendance  AssignmentScore   Marks
0          4.37       86.42            51.11   74.18
1          9.56       79.12            72.51  100.00
2          7.59       68.93            92.38   96.65
3          6.39       91.62            83.93   95.81
4          2.40       85.81            88.39   84.54
..          ...         ...              ...     ...
495        4.18       59.12            80.09   77.66
496        6.25       96.28            77.17  100.00
497        1.70       61.16            67.81   69.72
498        9.77       97.76            62.79  100.00
499        9.88       75.07            91.80  100.00

[500 rows x 4 columns]

In [9]:
x = df[["StudyHours"]]
x

     StudyHours
0          4.37
1          9.56
2          7.59
3          6.39
4          2.40
..          ...
495        4.18
496        6.25
497        1.70
498        9.77
499        9.88

[500 rows x 1 columns]

In [10]:
y = df[["Marks"]]
y

      Marks
0     74.18
1    100.00
2     96.65
3     95.81
4     84.54
..      ...
495   77.66
496  100.00
497   69.72
498  100.00
499  100.00

[500 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)
x_train

     StudyHours
249        8.68
433        1.91
19         3.62
322        6.94
332        1.13
..          ...
106        4.69
270        8.28
348        4.37
435        7.31
102        3.83

[400 rows x 1 columns]

In [12]:
x_test

     StudyHours
361        6.79
73         8.34
374        1.64
155        3.18
104        9.17
..          ...
347        1.41
86         7.57
75         7.56
438        7.36
15         2.65

[100 rows x 1 columns]

In [13]:
y_train

      Marks
249  100.00
433   77.48
19    65.60
322  100.00
332   56.75
..      ...
106   79.94
270  100.00
348   90.11
435   87.03
102   82.85

[400 rows x 1 columns]

In [14]:
y_test

      Marks
361   95.50
73   100.00
374   58.19
155   69.87
104  100.00
..      ...
347   79.30
86    95.75
75   100.00
438   90.82
15    71.52

[100 rows x 1 columns]

In [15]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [17]:
y_pred = lr.predict(x_test)
y_pred

array([[ 92.58143196],
       [ 98.85785117],
       [ 71.72752296],
       [ 77.96344915],
       [102.21877243],
       [ 81.56732857],
       [ 69.98632279],
       [ 77.43703979],
       [ 71.84900204],
       [ 97.44059522],
       [ 94.93002753],
       [ 81.48634251],
       [ 83.30852873],
       [ 80.47401683],
       [ 69.78385766],
       [ 96.50925559],
       [ 82.01275186],
       [ 91.28565509],
       [ 84.03740322],
       [102.13778637],
       [ 85.73811036],
       [ 91.73107839],
       [101.57088399],
       [ 70.10780187],
       [ 97.23813008],
       [ 92.78389709],
       [ 71.97048112],
       [ 94.36312515],
       [ 92.33847379],
       [ 70.79618334],
       [105.33673552],
       [100.31560015],
       [ 72.21343929],
       [ 77.39654677],
       [ 95.82087413],
       [ 73.34724405],
       [ 72.45639745],
       [ 97.27862311],
       [ 75.00745816],
       [ 82.13423095],
       [ 95.94235321],
       [ 89.58494795],
       [101.97581426],
       [ 93.18882737],
       [103.71701443],
       [ 71.84900204],
       [ 82.78211938],
       [104.48638195],
       [ 85.4951522 ],
       [ 79.78563537],
       [ 69.33843436],
       [102.82616783],
       [ 77.23457466],
       [ 80.75746802],
       [ 92.21699471],
       [102.74518178],
       [ 70.99864847],
       [ 84.88775679],
       [ 91.24516206],
       [ 82.215217  ],
       [ 86.02156155],
       [ 74.23809065],
       [ 79.34021207],
       [ 92.01452958],
       [ 73.34724405],
       [ 85.17120798],
       [ 89.50396189],
       [ 80.51450986],
       [ 92.66241801],
       [ 84.1588823 ],
       [ 93.14833434],
       [ 86.3859988 ],
       [ 92.82439012],
       [ 70.22928096],
       [ 75.45288146],
       [ 95.57791597],
       [ 82.25571003],
       [105.09377736],
       [ 87.07438026],
       [ 82.78211938],
       [105.05328433],
       [ 81.20289132],
       [ 89.30149676],
       [ 87.80325475],
       [ 95.1729857 ],
       [ 73.50921616],
       [ 81.56732857],
       [ 92.17650169],
       [ 70.06730885],
       [ 94.7275624 ],
       [ 94.52509726],
       [ 70.71519728],
       [ 85.81909642],
       [103.91947957],
       [ 96.87369284],
       [ 70.79618334],
       [ 95.73988808],
       [ 95.69939505],
       [ 94.88953451],
       [ 75.81731871]])

In [18]:
y_test

      Marks
361   95.50
73   100.00
374   58.19
155   69.87
104  100.00
..      ...
347   79.30
86    95.75
75   100.00
438   90.82
15    71.52

[100 rows x 1 columns]

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

mae = mean_absolute_error( y_test,y_pred)
mae

4.830776239314176

In [22]:

mse = mean_squared_error(y_pred, y_test)
mse

37.350048041927245

In [23]:
rmse = root_mean_squared_error(y_pred, y_test)
rmse

6.111468566713507

In [25]:
r2 = r2_score( y_test,y_pred)
r2

0.7496513676782813

In [26]:
n = len(y) #total no of rows

# it takes the columns out of shape
columns = x.shape[1]
columns

adj_r2 = 1 - ((1-r2) * (n-1) / (n-columns-1))
adj_r2

0.7491486595812498

In [30]:
# +1 study hour → predicted marks increase by about 4.05
lr.coef_

array([[4.04930272]])

In [ ]:
# Predicted marks when study hours = 0
lr.intercept_

array([65.0866665])